# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: healthMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import replyMessage_pb2 as replyMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13healthMessage.proto\x12\x0e\x43ustomAppProto\x1a\x12replyMessage.proto\"\x81\x02\n\rHealthMessage\x12\x0e\n\x06seq_no\x18\x01 \x01(\r\x12\n\n\x02ts\x18\x02 \x01(\x01\x12\x0c\n\x04name\x18\x03 \x01(\t\x12,\n\tdispenser\x18\x04 \x01(\x0e\x32\x19.CustomAppProto.Dispenser\x12\x10\n\x08icemaker\x18\x05 \x01(\x05\x12,\n\tlightbulb\x18\x06 \x01(\x0e\x32\x19.CustomAppProto.Lightbulb\x12\x13\n\x0b\x66ridge_temp\x18\x07 \x01(\x05\x12\x14\n\x0c\x66reezer_temp\x18\x08 \x01(\x05\x12-\n\rsensor_status\x18\t \x01(\x0e\x32\x16.CustomAppProto.Sensor*k\n\tDispenser\x12\x18\n\x14\x44ISPENSER_NOT_IN_USE\x10\x00\x12\x15\n\x11\x44ISPENSER_OPTIMAL\x10\x01\x12\x15\n\x11\x44ISPENSER_PARTIAL\x10\x02\x12\x16\n\x12\x44ISPENSER_BLOCKAGE\x10\x03*L\n\tLightbulb\x12\x18\n\x14LIGHTBULB_NOT_IN_USE\x10\x00\x12\x12\n\x0eLIGHTBULB_GOOD\x10\x01\x12\x11\n\rLIGHTBULB_BAD\x10\x02*@\n\x06Sensor\x12\x15\n\x11SENSOR_NOT_IN_USE\x10\x00\x12\x0f\n\x0bSENSOR_GOOD\x10\x01\x12\x0e\n\nSENSOR_BAD\x10\x02\x32X\n\rHealthService\x12G\n\x06method\x12\x1d.CustomAppProto.HealthMessage\x1a\x1c.CustomAppProto.ReplyMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'healthMessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DISPENSER']._serialized_start=319
  _globals['_DISPENSER']._serialized_end=426
  _globals['_LIGHTBULB']._serialized_start=428
  _globals['_LIGHTBULB']._serialized_end=504
  _globals['_SENSOR']._serialized_start=506
  _globals['_SENSOR']._serialized_end=570
  _globals['_HEALTHMESSAGE']._serialized_start=60
  _globals['_HEALTHMESSAGE']._serialized_end=317
  _globals['_HEALTHSERVICE']._serialized_start=572
  _globals['_HEALTHSERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
