# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class BreadType(object):
    AREPA = 0
    BAGUETTE = 1
    BAGEL = 2
    BRIOCHE = 3
    CIABATTA = 4
    CHALLAH = 5
    ENGLISH_MUFFIN = 6
    FOCACCIA = 7
    HOKKAIDO = 8
    IRISH_SODA_BREAD = 9
    MULTIGRAIN = 10
    NAAN = 11
    PARATHA = 12
    PITA = 13
    RYE_BREAD = 14
    SOURDOUGH = 15
    WHITE_BREAD = 16
    WHOLE_WHEAT_BREAD = 17
