# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class CanType(object):
    COCA_COLA = 0
    PEPSI = 1
    DIET_COKE = 2
    DR_PEPPER = 3
    MOUNTAIN_DEW = 4
    SPRITE = 5
    DEIT_PEPSI = 6
    COKE_ZERO = 7
    DIET_DR_PEPPER = 8
    FANTA = 9
    SIERRA_MIST = 10
    SUNKIST = 11
    TAB = 12
