# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class MeatType(object):
    PORK = 0
    CHICKEN = 1
    BEEF = 2
    LAMB = 3
    GOAT = 4
    TURKEY = 5
    DUCK = 6
    BUFFALO = 7
    GOOSE = 8
    RABBIT = 9
