# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Meat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Meat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Meat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Meat
    def Xtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Meat
    def Xquantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def MeatStart(builder):
    builder.StartObject(2)

def Start(builder):
    MeatStart(builder)

def MeatAddXtype(builder, xtype):
    builder.PrependInt8Slot(0, xtype, 0)

def AddXtype(builder, xtype):
    MeatAddXtype(builder, xtype)

def MeatAddXquantity(builder, xquantity):
    builder.PrependFloat32Slot(1, xquantity, 0.0)

def AddXquantity(builder, xquantity):
    MeatAddXquantity(builder, xquantity)

def MeatEnd(builder):
    return builder.EndObject()

def End(builder):
    return MeatEnd(builder)
