# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class VegType(object):
    TOMATO = 0
    CUCUMBER = 1
    POTATO = 2
    CARROT = 3
    SPINACH = 4
    LETTUCE = 5
    BROCCOLI = 6
    CAULIFLOWER = 7
    BOK_CHOY = 8
    ONION = 9
    GARLIC = 10
    GREEN_BEANS = 11
    PEAS = 12
