# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replyMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12replyMessage.proto\x12\x0e\x43ustomAppProto\"\x92\x01\n\x0cReplyMessage\x12\x0e\n\x06seq_no\x18\x01 \x01(\r\x12\n\n\x02ts\x18\x02 \x01(\x01\x12\x33\n\rreply_request\x18\x03 \x01(\x0e\x32\x1c.CustomAppProto.ReplyRequest\x12\x31\n\x0creply_status\x18\x04 \x01(\x0e\x32\x1b.CustomAppProto.ReplyStatus*<\n\x0cReplyRequest\x12\x19\n\x15REPLY_REQUEST_NOT_SET\x10\x00\x12\x08\n\x04GOOD\x10\x01\x12\x07\n\x03\x42\x41\x44\x10\x02*I\n\x0bReplyStatus\x12\x18\n\x14REPLY_STATUS_NOT_SET\x10\x00\x12\x0e\n\nSUCCESSFUL\x10\x01\x12\x10\n\x0cUNSUCCESSFUL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replyMessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REPLYREQUEST']._serialized_start=187
  _globals['_REPLYREQUEST']._serialized_end=247
  _globals['_REPLYSTATUS']._serialized_start=249
  _globals['_REPLYSTATUS']._serialized_end=322
  _globals['_REPLYMESSAGE']._serialized_start=39
  _globals['_REPLYMESSAGE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
