# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class MilkType(object):
    ONEPERCENT = 0
    TWOPERCENT = 1
    FATFREE = 2
    WHOLE = 3
    ALMOND = 4
    CASHEW = 5
    OAT = 6
